### ISSUE TITLE
Can't load flag icon for some countries on macOS

### ISSUE THREAD

**Issue by eukurapov** [KELiON/cerebro-timezones#1]
App can't load flag icon for some countries on macOS and search result overlaps with image path.
Appears on macOS Sierra (10.12.3)
Examples:
![screen shot 2017-02-15 at 13 09 35](https://cloud.githubusercontent.com/assets/25790922/22969867/0e24ab38-f381-11e6-9da4-ac8085f593b5.png)
![screen shot 2017-02-15 at 13 10 35](https://cloud.githubusercontent.com/assets/25790922/22969866/0e222fc0-f381-11e6-8085-a9ab73605fb8.png)

**Comment by KELiON** [comment]
@eukurapov wow, after that comment I found an interesting bug in MacOS. If you go to the folder → <kbd>cmd+a</kbd> → go to another folder → <kbd>cmd+option+v</kbd> (select all files, cut and paste) → only 128 files moved, instead of all of them. 

Anyway, update to v0.0.2 will fix this bug

**Comment by eukurapov** [comment]
can't reproduce macos bug.

this one seems fixed.

btw, how to update plugin? (this time I've done uninstall + install)

**Comment by KELiON** [comment]
@eukurapov there should be `update` item in plugin preview:

<img width="390" alt="screen shot 2017-02-15 at 12 05 25" src="https://cloud.githubusercontent.com/assets/594298/22971756/0ffb993a-f377-11e6-8566-91019ae55565.png">

that actually do the same (uninstall + install). Looks like in your case plugins versions were cached
