### ISSUE TITLE
Incorrect timezones when user is in DST

### ISSUE THREAD

**Issue by brahma-dev** [KELiON/cerebro-timezones#4]
![cerebro-timezones](https://cloud.githubusercontent.com/assets/1793295/26151173/d7b4e374-3b01-11e7-9a87-41fd61f01a00.png)

New Delhi is +5:30
I am in Spain with DST active these days.

**Comment by KELiON** [comment]
Hi, @afzaalace! Thanks for the issue, I've fixed it in version 0.0.5:
![image](https://cloud.githubusercontent.com/assets/594298/26151972/5eb45bea-3b05-11e7-943c-02f45ab75654.png)

BTW, it used to show time correctly, but timezone offset was incorrect. It was the case for timezones with 30/15 minutes offsets.
